### ISSUE TITLE
Go Modules

### ISSUE THREAD

**Issue by njhale** [ibuildthecloud/k3v#3]
I think using a dependency manager will help when playing with this project locally. It will also make builds reproducible.

@ibuildthecloud any thoughts on using go modules here? If so, would you accept a contribution for it?

**Comment by ibuildthecloud** [comment]
Go modules with k8s is currently a disaster.  Recently went on a rant about this. https://twitter.com/ibuildthecloud/status/1151626526225338368?s=20

I'll update the project with proper dependency tool.  Right now the deps are a mess.  The reason I didn't check in some deps files is because the vendor folder is currently hacked up.  I'll get things cleaned up as there seems to be sufficient interest in this by the community.

**Comment by njhale** [comment]
Thanks for the quick response! That's understandable. I've had a pretty similar experience using modules with k/k and staging repos - although I will say pinning `release-1.Y` branches with `replace` directives works fairly ~painlessly~ consistently.
